export const DISEASE_CATEGORIES = [
  {
    id: 'infectious',
    name: 'Infectious Skin Diseases',
    description: 'Caused by bacteria, viruses, fungi, or parasites',
    icon: 'Bug',
    color: 'medical-coral',
    subcategories: [
      { name: 'Bacterial', diseases: ['Impetigo', 'Cellulitis', 'Erysipelas', 'Folliculitis', 'Boils', 'Carbuncle', 'Leprosy'] },
      { name: 'Viral', diseases: ['Warts', 'Herpes Simplex', 'Shingles', 'Chickenpox', 'Measles', 'Molluscum Contagiosum'] },
      { name: 'Fungal', diseases: ['Ringworm', 'Athlete\'s Foot', 'Jock Itch', 'Nail Fungus', 'Candidiasis', 'Pityriasis Versicolor'] },
      { name: 'Parasitic', diseases: ['Scabies', 'Pediculosis', 'Cutaneous Larva Migrans'] },
    ],
  },
  {
    id: 'inflammatory',
    name: 'Inflammatory & Allergic',
    description: 'Due to immune reaction or allergy',
    icon: 'Flame',
    color: 'medical-orange',
    diseases: ['Eczema', 'Contact Dermatitis', 'Seborrheic Dermatitis', 'Psoriasis', 'Urticaria', 'Angioedema', 'Lichen Planus', 'Prurigo Nodularis'],
  },
  {
    id: 'acne',
    name: 'Acne & Sebaceous',
    description: 'Related to oil glands',
    icon: 'Droplet',
    color: 'medical-blue',
    diseases: ['Acne Vulgaris', 'Acne Rosacea', 'Blackheads & Whiteheads', 'Sebaceous Cyst', 'Hidradenitis Suppurativa'],
  },
  {
    id: 'pigmentation',
    name: 'Pigmentation Disorders',
    description: 'Affect skin color',
    icon: 'Palette',
    color: 'medical-purple',
    diseases: ['Vitiligo', 'Melasma', 'Hyperpigmentation', 'Hypopigmentation', 'Albinism', 'Freckles', 'Lentigines'],
  },
  {
    id: 'genetic',
    name: 'Genetic & Congenital',
    description: 'Present from birth or inherited',
    icon: 'Dna',
    color: 'medical-green',
    diseases: ['Ichthyosis', 'Epidermolysis Bullosa', 'Xeroderma Pigmentosum', 'Neurofibromatosis', 'Albinism', 'Birthmarks'],
  },
  {
    id: 'autoimmune',
    name: 'Autoimmune Diseases',
    description: 'Immune system attacks the skin',
    icon: 'Shield',
    color: 'medical-teal',
    diseases: ['Lupus Erythematosus', 'Scleroderma', 'Dermatomyositis', 'Pemphigus Vulgaris', 'Bullous Pemphigoid', 'Alopecia Areata'],
  },
  {
    id: 'hair',
    name: 'Hair & Scalp Disorders',
    description: 'Affect hair growth and scalp',
    icon: 'Scissors',
    color: 'medical-coral',
    diseases: ['Alopecia Areata', 'Androgenic Alopecia', 'Dandruff', 'Telogen Effluvium', 'Scalp Psoriasis', 'Tinea Capitis'],
  },
  {
    id: 'nail',
    name: 'Nail Disorders',
    description: 'Affect fingernails and toenails',
    icon: 'Hand',
    color: 'medical-orange',
    diseases: ['Nail Fungus', 'Ingrown Nail', 'Nail Psoriasis', 'Clubbing', 'Onycholysis', 'Brittle Nail Syndrome'],
  },
  {
    id: 'cancer',
    name: 'Skin Tumors & Cancers',
    description: 'Abnormal growth of skin cells',
    icon: 'AlertTriangle',
    color: 'destructive',
    subcategories: [
      { name: 'Benign', diseases: ['Lipoma', 'Seborrheic Keratosis', 'Skin Tags', 'Dermatofibroma'] },
      { name: 'Malignant', diseases: ['Basal Cell Carcinoma', 'Squamous Cell Carcinoma', 'Melanoma', 'Merkel Cell Carcinoma'] },
    ],
  },
  {
    id: 'other',
    name: 'Other Conditions',
    description: 'Common skin conditions',
    icon: 'MoreHorizontal',
    color: 'muted-foreground',
    diseases: ['Corns & Calluses', 'Wounds & Ulcers', 'Burns', 'Pressure Sores', 'Stretch Marks', 'Keloids', 'Sunburn'],
  },
];

export const LOCATIONS = [
  'Coimbatore',
  'Chennai',
  'Bangalore',
  'Hyderabad',
  'Mumbai',
  'Delhi',
  'Kolkata',
  'Pune',
];
