interface ReportData {
  disease: string;
  confidence: number;
  description: string;
  symptoms: string[];
  remedies: string[];
  whenToSeeDoctor: string;
  prevention: string[];
  date: string;
  patientEmail?: string;
}

export function generateReport(data: ReportData) {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Skin Detection Report - ${data.disease}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1a1a2e; padding: 40px; max-width: 800px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 3px solid #0d9488; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { font-size: 24px; color: #0d9488; margin-bottom: 4px; }
        .header p { color: #666; font-size: 13px; }
        .meta { display: flex; justify-content: space-between; background: #f0fdfa; padding: 12px 16px; border-radius: 8px; margin-bottom: 24px; font-size: 13px; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
        .badge-primary { background: #ccfbf1; color: #0d9488; }
        .badge-green { background: #dcfce7; color: #16a34a; }
        .result-header { margin-bottom: 20px; }
        .result-header h2 { font-size: 22px; margin-top: 8px; }
        .section { margin-bottom: 24px; }
        .section h3 { font-size: 15px; font-weight: 600; margin-bottom: 10px; padding-bottom: 6px; border-bottom: 1px solid #e5e7eb; color: #0d9488; }
        .section p { font-size: 14px; line-height: 1.6; color: #374151; }
        .tags { display: flex; flex-wrap: wrap; gap: 6px; }
        .tag { padding: 4px 10px; background: #f3f4f6; border-radius: 16px; font-size: 12px; }
        ul { list-style: none; padding: 0; }
        ul li { font-size: 13px; line-height: 1.5; padding: 5px 0; padding-left: 18px; position: relative; }
        ul li::before { content: "✓"; position: absolute; left: 0; color: #16a34a; font-weight: bold; }
        .warning { background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 14px; margin-bottom: 24px; }
        .warning h3 { color: #dc2626; border: none; padding: 0; margin-bottom: 6px; }
        .warning p { color: #991b1b; font-size: 13px; }
        .prevention-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
        .prevention-item { background: #f9fafb; padding: 8px 12px; border-radius: 6px; font-size: 13px; }
        .prevention-num { color: #0d9488; font-weight: 700; margin-right: 6px; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🩺 Skin Disease Detection Report</h1>
        <p>AI-Powered Analysis Report</p>
      </div>

      <div class="meta">
        <span><strong>Date:</strong> ${data.date}</span>
        ${data.patientEmail ? `<span><strong>Patient:</strong> ${data.patientEmail}</span>` : ''}
      </div>

      <div class="result-header">
        <span class="badge badge-primary">AI Detection Result</span>
        <span class="badge badge-green">${data.confidence}% confidence</span>
        <h2>${data.disease}</h2>
      </div>

      <div class="section">
        <h3>Description</h3>
        <p>${data.description}</p>
      </div>

      <div class="section">
        <h3>Symptoms</h3>
        <div class="tags">
          ${data.symptoms.map(s => `<span class="tag">${s}</span>`).join('')}
        </div>
      </div>

      <div class="section">
        <h3>Recommended Remedies</h3>
        <ul>
          ${data.remedies.map(r => `<li>${r}</li>`).join('')}
        </ul>
      </div>

      <div class="warning">
        <h3>⚠ When to See a Doctor</h3>
        <p>${data.whenToSeeDoctor}</p>
      </div>

      <div class="section">
        <h3>Prevention Tips</h3>
        <div class="prevention-grid">
          ${data.prevention.map((p, i) => `<div class="prevention-item"><span class="prevention-num">${i + 1}.</span>${p}</div>`).join('')}
        </div>
      </div>

      <div class="footer">
        <p><strong>Disclaimer:</strong> This report is generated by AI for educational purposes only. Always consult a healthcare professional for proper diagnosis and treatment.</p>
        <p style="margin-top: 8px;">Generated by SkinGuard AI • ${data.date}</p>
      </div>
    </body>
    </html>
  `;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, '_blank');
  if (printWindow) {
    printWindow.onload = () => {
      printWindow.print();
    };
  }
}
